environment:
  TARGET: 1.15.0-x86_64-pc-windows-gnu
  MSYS2_BITS: 64
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe"
  - rust-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V
  - ps: Start-FileDownload 'https://sqlite.org/2017/sqlite-dll-win64-x64-3170000.zip' # download SQLite dll (useful only when the `bundled` feature is not set)
  - cmd: 7z e sqlite-dll-win64-x64-3170000.zip -y > nul
  - ps: Start-FileDownload 'https://sqlite.org/2017/sqlite-amalgamation-3170000.zip' # download SQLite headers (useful only when the `bundled` feature is not set)
  - cmd: 7z e sqlite-amalgamation-3170000.zip -y > nul
  - SET SQLITE3_LIB_DIR=%APPVEYOR_BUILD_FOLDER% # specify where the SQLite dll has been downloaded (useful only when the `bundled` feature is not set)
  - SET SQLITE3_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER% # specify where the SQLite headers have been downloaded (useful only when the `bundled` feature is not set)

build: false

test_script:
  - cargo test --lib --verbose
  - cargo test --lib --verbose --features bundled
  - cargo test --lib --features "backup blob chrono functions limits load_extension serde_json trace"
  - cargo test --lib --features "backup blob chrono functions limits load_extension serde_json trace bundled"

cache:
  - C:\Users\appveyor\.cargo
