[package]
name = "libsql-sys"
version = "0.2.14"
edition = "2021"
license = "MIT"
description = "Native bindings to libSQL"
repository = "https://github.com/tursodatabase/libsql"
keywords = ["libsql", "sqlite", "ffi", "bindings", "database"]
categories = ["external-ffi-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
tracing = "0.1.37"
libsql-ffi =  { path = "../libsql-ffi/" }

[features]
session = []
