[package]
name = "libsqlite3-sys"
version = "0.0.11"
authors = ["John Gallagher <jgallagher@bignerdranch.com>"]
repository = "https://github.com/jgallagher/rusqlite"
description = "Native bindings to the libsqlite3 library"
license = "MIT"
links = "sqlite3"
build = "build.rs"

[features]
load_extension = []

[build-dependencies]
pkg-config = "~0.3"
