[package]
name = "libsqlite3-sys"
version = "0.7.1"
authors = ["John Gallagher <jgallagher@bignerdranch.com>"]
repository = "https://github.com/jgallagher/rusqlite"
description = "Native bindings to the libsqlite3 library"
license = "MIT"
links = "sqlite3"
build = "build.rs"
keywords = ["sqlite", "database", "ffi"]
categories = ["database", "external-ffi-bindings"]

[features]
bundled = []

[build-dependencies]
bindgen = "0.21"
pkg-config = "0.3"
gcc = "0.3"
