[package]
name = "sqld"
version = "0.15.0"
edition = "2021"
default-run = "sqld"

[dependencies]
anyhow = "1.0.66"
async-lock = "2.6.0"
async-trait = "0.1.58"
base64 = "0.21.0"
bincode = "1.3.3"
bottomless = { version = "0", path = "../bottomless", features = ["libsql_linked_statically"], optional = true }
bytemuck = { version = "1.13.0", features = ["derive"] }
bytes = { version = "1.2.1", features = ["serde"] }
bytesize = "1.2.0"
clap = { version = "4.0.23", features = [ "derive", "env"] }
console-subscriber = { version = "0.1.9", optional = true }
crc = "3.0.0"
crossbeam = "0.8.2"
enclose = "1.1"
fallible-iterator = "0.2.0"
futures = "0.3.25"
hmac = "0.12"
hyper = { version = "0.14.23", features = ["http2"] }
hyper-tungstenite = "0.10"
itertools = "0.10.5"
jsonwebtoken = "8.2.0"
memmap = "0.7.0"
mimalloc = { version = "0.1.36", default-features = false }
nix = { version = "0.26.2", features = ["fs"] }
once_cell = "1.17.0"
parking_lot = "0.12.1"
priority-queue = "1.3"
prost = "0.11.3"
rand = "0.8"
regex = "1.7.0"
reqwest = { version = "0.11.16", features = ["json", "rustls-tls"], default-features = false }
rusqlite = { workspace = true }
serde = { version = "1.0.149", features = ["derive", "rc"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
sha2 = "0.10"
sha256 = "1.1.3"
sqld-libsql-bindings = { version = "0", path = "../sqld-libsql-bindings" }
sqlite3-parser = { version = "0.8.0", default-features = false, features = [ "YYNOERRORRECOVERY" ] }
tempfile = "3.3.0"
thiserror = "1.0.38"
tokio = { version = "1.22.2", features = ["rt-multi-thread", "net", "io-std", "io-util", "time", "macros", "sync", "fs"] }
tokio-stream = "0.1.11"
tokio-tungstenite = "0.19"
tonic = { version = "0.8.3", features = ["tls"] }
tower = { version = "0.4.13", features = ["make"] }
tower-http = { version = "0.3.5", features = ["compression-full", "cors", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.3", features = ["v4", "serde"] }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.5"
tempfile = "3.3.0"
insta = { version = "1.26.0", features = ["json"] }
arbitrary = { version = "1.3.0", features = ["derive_arbitrary"] }

[build-dependencies]
prost-build = "0.11.4"
tonic-build = "0.8.4"
vergen = { version = "8", features = ["build", "git", "gitcl"] }

[features]
unix-excl-vfs = ["sqld-libsql-bindings/unix-excl-vfs"]
bottomless = ["dep:bottomless"]
debug-tools = ["console-subscriber", "rusqlite/trace", "tokio/tracing"]
