[package]
name = "sqld"
version = "0.11.0"
edition = "2021"
default-run = "sqld"

[dependencies]
anyhow = "1.0.66"
async-lock = "2.6.0"
async-trait = "0.1.58"
base64 = "0.21.0"
bincode = "1.3.3"
bottomless = { version = "0", path = "../bottomless", features = ["libsql_linked_statically"], optional = true }
byteorder = "1.4.3"
bytemuck = { version = "1.13.0", features = ["derive"] }
bytes = { version = "1.2.1", features = ["serde"] }
clap = { version = "4.0.23", features = [ "derive", "env"] }
crc = "3.0.0"
crossbeam = "0.8.2"
enclose = "1.1"
fallible-iterator = "0.2.0"
futures = "0.3.25"
hex = "0.4.3"
hyper = { version = "0.14.23", features = ["http2"] }
hyper-tungstenite = "0.9"
itertools = "0.10.5"
jsonwebtoken = "8.2.0"
once_cell = "1.17.0"
parking_lot = "0.12.1"
pgwire = "0.11.1"
pin-project-lite = "0.2.9"
postgres-protocol = "0.6.4"
prost = "0.11.3"
regex = "1.7.0"
rusqlite = { version = "0.29.0", git = "https://github.com/psarna/rusqlite", rev = "a6332e530f30dc2d47110", default-features = false, features = [
    "buildtime_bindgen",
    "bundled-libsql-wasm-experimental",
    "column_decltype",
    "load_extension"
] }
serde = { version = "1.0.149", features = ["derive", "rc"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
smallvec = "1.10.0"
sqld-libsql-bindings = { version = "0", path = "../sqld-libsql-bindings" }
sqlite3-parser = { version = "0.6.0", default-features = false, features = [ "YYNOERRORRECOVERY" ] }
thiserror = "1.0.38"
tokio = { version = "1.22.2", features = ["rt-multi-thread", "net", "io-std", "io-util", "time", "macros", "sync", "fs"] }
tokio-stream = "0.1.11"
tokio-tungstenite = "0.18"
tokio-util = "0.7.4"
tonic = { version = "0.8.3", features = ["tls"] }
tower = { version = "0.4.13", features = ["make"] }
tower-http = { version = "0.3.5", features = ["compression-full", "cors", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
nix = { version = "0.26.2", features = ["fs"] }
tempfile = "3.3.0"
memmap = "0.7.0"
mimalloc = "0.1.36"
sha256 = "1.1.3"

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.5"
tempfile = "3.3.0"
insta = { version = "1.26.0", features = ["json"] }

[build-dependencies]
prost-build = "0.11.4"
tonic-build = "0.8.4"
vergen = "6"

[features]
mwal_backend = ["sqld-libsql-bindings/mwal_backend"]
unix-excl-vfs = ["sqld-libsql-bindings/unix-excl-vfs"]
bottomless = ["dep:bottomless"]
