[package]
name = "sqld"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-lock = "2.6.0"
async-trait = "0.1.58"
bincode = "1.3.3"
byteorder = "1.4.3"
bytes = "1.2.1"
clap = { version = "4.0.23", features = [ "derive" ] }
crossbeam = "0.8.2"
foundationdb = { version = "0.7.0", features = ["embedded-fdb-include"], optional = true }
futures = "0.3.25"
hex = "0.4.3"
# Regular mvfs prevents users from enabling WAL mode
mvfs = { git = "https://github.com/psarna/mvsqlite", branch = "mwal" }
mwal = { git = "https://github.com/psarna/mvsqlite", branch = "mwal" }
parking_lot = "0.12.1"
pgwire = "0.7.0"
pin-project-lite = "0.2.9"
postgres-protocol = "0.6.4"
prost = "0.11.3"
rusqlite = { version = "0.28.0", features = [ "buildtime_bindgen", "column_decltype" ] }
serde = { version = "1.0.149", features = ["derive"] }
smallvec = "1.10.0"
sqlparser = "0.27.0"
tokio = { version = "1.21.2", features = ["full"] }
tokio-tungstenite = "0.17.2"
tokio-util = "0.7.4"
tonic = "0.8.3"
tower = { version = "0.4.13", features = ["make"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
uuid = { version = "1.2.2", features = ["v4"] }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.5"

[build-dependencies]
tonic-build = "0.8.4"

[features]
fdb = ["foundationdb"]
