[package]
name = "libsql-wasmtime-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "2.0"

[lib]
name = "wblibsql"
crate-type = ["rlib", "cdylib", "staticlib"]
doc = false
test = false
doctest = false

[profile.release]
opt-level = "s"
strip = true
debug = false
panic = "abort"

[workspace]
