[package]
name = "libsql_core"
version = "0.0.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
libsql-sys = { path = "../libsql-sys" }
thiserror = "1.0.40"
libsql_replication = { path = "../replication" }
tokio = { version = "1.29.1", features = ["macros"] }
tracing-subscriber = "0.3.17"
tracing = "0.1.37"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports", "async", "async_futures"] }
pprof = { version = "0.11.1", features = ["criterion", "flamegraph"] }

[[bench]]
name = "benchmark"
harness = false
