name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: get TCL
      run: sudo apt-get install -y tcl8.6-dev

    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: configure
      run: ./configure
      
    - name: Run tests
      run: make test

    - name: Run Rust tests
      run: make rusttest

    - name: Run API tests
      run: make libsqlapi
