name: Makefile CI with Wasm enabled

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: get TCL
      run: sudo apt-get install -y tcl8.6-dev

    - name: rustup
      run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -qy --default-toolchain `cat src/rust/wasmtime-bindings/rust-toolchain`"

    - name: configure with Wasm
      run: ./configure --enable-wasm-runtime

    - name: make the library generally available
      run: sudo make liblibsql_install
      
    - name: Run tests
      run: make test

    - name: Run Rust tests with Wasm
      run: make rusttestwasm
