name: Makefile CI with Wasm enabled

on:
  push:
    branches: [ "main" ]
    paths:
      - "libsql-sqlite3/**"
  pull_request:
    paths:
      - "libsql-sqlite3/**"
  merge_group:
    branches: [ "main" ]
    paths:
      - "libsql-sqlite3/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  make-sqlite3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libsql-sqlite3

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    
    - name: get TCL
      run: sudo apt-get install -y tcl8.6-dev

    - name: get WasmEdge
      run: > 
        wget -O- https://github.com/WasmEdge/WasmEdge/releases/download/0.11.2/WasmEdge-slim-runtime-0.11.2-manylinux2014_x86_64.tar.gz | tar zxv
        && sudo cp -r WasmEdge-0.11.2-Linux/include/* /usr/include/
        && sudo cp -r WasmEdge-0.11.2-Linux/lib64/* /usr/lib/

    - name: configure with Wasm
      run: ./configure --enable-wasm-runtime-dynamic

    - name: make the library generally available
      run: mkdir tmp_lib && DESTDIR=$(pwd)/tmp_lib  make liblibsql_install && sudo cp -r tmp_lib/usr/local/lib/* /usr/lib/
      
    - name: Run tests
      run: make test

    - name: Run Rust tests with Wasm
      run: make rusttestwasm
